# Delegates to the shared release workflow in cap-js/.github
# For more information see: https://github.com/cap-js/.github



name: Release

on:
  push:
    branches: main

  workflow_dispatch:
    inputs:
      dry-run:
        description: Dry run
        required: false
        default: false
        type: boolean

permissions:
  contents: write
  id-token: write

concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true


jobs:
  release:
    uses: cap-js/.github/.github/workflows/release.yml@main
    secrets: inherit
    with:
      dry-run: ${{ fromJSON(github.event.inputs.dry-run || 'false') }}
